language: php
php:
  - '7.4'

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - vendor/bin/psalm --show-info=true
  - vendor/bin/phpstan analyse -c phpstan.neon
  - vendor/bin/phpunit